// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRCVu0uGHGzViuBkEeseJagJe8yvU2zCs',
    appId: '1:607724776234:web:f4b6668769167532d04c53',
    messagingSenderId: '607724776234',
    projectId: 'cricketconnect-d3945',
    authDomain: 'cricketconnect-d3945.firebaseapp.com',
    storageBucket: 'cricketconnect-d3945.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ1OUV7zLihzetUGYsApkPqYzp2g58FQw',
    appId: '1:607724776234:android:910e159b6729db38d04c53',
    messagingSenderId: '607724776234',
    projectId: 'cricketconnect-d3945',
    storageBucket: 'cricketconnect-d3945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkj7LipJWn3M0OHr_3UrWE5pK-XQyR8cw',
    appId: '1:607724776234:ios:34be3ace2082be03d04c53',
    messagingSenderId: '607724776234',
    projectId: 'cricketconnect-d3945',
    storageBucket: 'cricketconnect-d3945.firebasestorage.app',
    iosBundleId: 'com.example.crickettConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkj7LipJWn3M0OHr_3UrWE5pK-XQyR8cw',
    appId: '1:607724776234:ios:34be3ace2082be03d04c53',
    messagingSenderId: '607724776234',
    projectId: 'cricketconnect-d3945',
    storageBucket: 'cricketconnect-d3945.firebasestorage.app',
    iosBundleId: 'com.example.crickettConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRCVu0uGHGzViuBkEeseJagJe8yvU2zCs',
    appId: '1:607724776234:web:3bed8a75f1b7aba5d04c53',
    messagingSenderId: '607724776234',
    projectId: 'cricketconnect-d3945',
    authDomain: 'cricketconnect-d3945.firebaseapp.com',
    storageBucket: 'cricketconnect-d3945.firebasestorage.app',
  );
}
